//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Event
    {
        public int EventID { get; set; }
        [DisplayName("Image")]
        public string ImagePath { get; set; }
        [DisplayName("Name")]
        public string Title { get; set; }
        [DisplayName("Type")]
        public string Type { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }
        [DisplayName("Startime of the event")]
        public string StartTime { get; set; }
        [DisplayName("Endtime pf the event")]
        public string EndTime { get; set; }
        [DisplayName("Price")]
        public double Price { get; set; }
        [DisplayName("The rating")]
        public int Rating { get; set; }
        [DisplayName("Is the category active?")]
        public bool IsActive { get; set; }
        [DisplayName("Is the category to be deleted?")]
        public bool IsDeleted { get; set; }
        [DisplayName("Is the category featured?")]
        public bool IsFeatured { get; set; }
        [DisplayName("Category")]
        public int CategoryID { get; set; }
        [DisplayName("Location")]
        public int LocationID { get; set; }
    
        public  Category Category { get; set; }
        public Location Location { get; set; }
    }
}
